# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.CharField(default='www.google.ca', max_length=50),
            preserve_default=False,
        ),
    ]
