# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.CharField(default='plot', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='rated',
            field=models.CharField(default='PG', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.CharField(default='2 mins', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='tracking',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(default='2017', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
