# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20170211_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='quality',
            field=models.CharField(blank=True, choices=[('A', 'Great'), ('B', 'Good'), ('C', 'Okay'), ('D', 'Poor')], max_length=1),
        ),
    ]
